default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: calendoration_development
  username: postgres
  password: root
  host: localhost
  port: 5432

test:
  <<: *default
  database: calendoration_test
  username: postgres
  password: root
  host: localhost
  port: 5432

production:
  <<: *default
  database: calendoration_production
  username: postgres
  password: root
  host: localhost
  port: 5432
